// utils/openai.js
// Provides a simple wrapper for a WebRTC connection to the OpenAI Realtime API.
// In this minimal example we simply simulate incoming messages using EventTarget.

export function createRealtimeConnection() {
  const connection = new EventTarget();

  // Simulate incoming transcript and response messages
  setTimeout(() => {
    connection.dispatchEvent(
      new CustomEvent('transcript', { detail: 'Simulated transcript from OpenAI.' })
    );
  }, 1000);

  setTimeout(() => {
    connection.dispatchEvent(
      new CustomEvent('response', { detail: 'Simulated answer generated by OpenAI.' })
    );
  }, 1500);

  // Simulate a potential error to showcase logging
  setTimeout(() => {
    connection.dispatchEvent(
      new CustomEvent('error', { detail: 'Simulated connection error.' })
    );
  }, 2000);

  return connection;
}
